[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my-first-ph3-package"
version = "0.1.0"
description = "Python Boilerplate contains all the boilerplate you need to create a Python package."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Fabien Mathieu", email = "fabien.mathieu@normalesup.org"}
]
maintainers = [
    {name = "Fabien Mathieu", email = "fabien.mathieu@normalesup.org"}
]
license = "MIT"
dependencies = [
"click>=8.1.8",

]

[project.urls]
Repository = "https://github.com/balouf/my-first-ph3-package"
Documentation = "https://balouf.github.io/my-first-ph3-package"

[dependency-groups]
dev = [
    "ipython>=8.35.0",
    "myst-parser[linkify]>=4.0.1",
    "nbsphinx>=0.9.7",
    "pydata-sphinx-theme>=0.16.1",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.8",
    "sphinx-copybutton>=0.5.2"
]

[project.scripts]
my_first_ph3_package = 'my_first_ph3_package.cli:main'


[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["my_first_ph3_package"]

[tool.coverage.html]
directory = "cov"

[tool.pytest.ini_options]
addopts = "--doctest-modules --cov --cov-config=pyproject.toml --cov-report xml --cov-report html --showlocals --capture=no --exitfirst --failed-first"
